### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/dune_processes#77]

**Comment by alexdewar** [comment]
It looks like @dalonsoa's PR #79 raises the coverage to 82% overall. Every file except `_production.py` has 100% coverage.

I think this is good enough for now so I suggest we close this.

**Comment by cc-a** [comment]
Could configure `_production.py` to be ignored as by it's nature it wouldn't be covered by tests?

**Comment by alexdewar** [comment]
Good idea. Maybe you could do this in your PR @dalonsoa?
