### ISSUE TITLE
Apply bootswatch theme

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/dune_processes#95]
Pick one from https://bootswatch.com/. Dune team didn't have any strong preferences. Once implemented it's easy to change later anyway.

See example implementation in settings - https://github.com/ImperialCollegeLondon/QwikApp_web/blob/30f1d3109c3866dac5dafeeb74b92be3e3231f11/qwikapp/settings/settings.py#L210-L223.

**Comment by dalonsoa** [comment]
Duplicated of #72

**Comment by cc-a** [comment]
Good point @dalonsoa.
